- name: update sysctl values
  become: true
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  with_items: "{{ sysctl_vars }}"
  tags:
  - sysctl
  - system

- name: update sysrc vars
  become: true
  community.general.sysrc:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  with_items: "{{ sysrc_vars }}"
  tags:
  - sysrc
  - etc
  - system
